import styles from "./index.module.css"
import type { GetStaticPropsContext, NextPage } from "next"
import Head from "next/head"
import Link from "next/link"

import { useTranslation, Trans } from "next-i18next"

import { serverSideTranslations } from "next-i18next/serverSideTranslations"

export async function getStaticProps(context: GetStaticPropsContext) {
  const { locale } = context

  return {
    props: {
      ...(await serverSideTranslations(locale as string, ["common", "documents"])),
      // Will be passed to the page component as props
    },
  }
}

const Home: NextPage = () => {
  const { t } = useTranslation(["common", "documents"])
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            Create <span className={styles.pinkSpan}>T3</span> App
          </h1>
          <Trans
            i18nKey="hero_text"
            ns={["documents", "common"]}
            t={t}
            components={[
              <span
                style={{
                  color: "purple",
                }}
              />,
            ]}
          />
        </div>
      </main>
    </>
  )
}

export default Home
